version: '3'

services:
  api-118:
    build: ./API_118
    container_name: api-118
    ports:
      - "3118:3000"
    restart: unless-stopped

  api-pharmacy:
    build: ./API_pharmacy
    container_name: api-pharmacy
    ports:
      - "3000:3000"
    restart: unless-stopped

  camunda:
    image: camunda/camunda-bpm-platform
    container_name: camunda
    ports:
      - "8080:8080"

  workers:
    build: ./camunda_workers
    container_name: camunda-workers
    depends_on:
      - camunda